# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Certain Uncertainty
email: leehkenny@gmail.com
description: In search of meaningful correlations around the world <br> Blog by Kenny Lee
baseurl: "/blog/" # the subpath of your site, e.g. /blog
url: "http://127.0.0.1:4000"
# url: "http://kennylee15.github.io" # the base hostname & protocol for your site
github_username:  kennylee15
linkedin_username: kennylee16
personalpage: kennylee.info
# Build settings
markdown: kramdown
